ServiceHost = "0.0.0.0"
ServicePort = 8080

[MinIO]
Endpoint = "127.0.0.1:9000"
AccessKeyID = "minio"
SecretAccessKey = "minio124"
UseSSL = false
BucketName = "books"

# НАСТРОЙКИ Redis
[Redis]
# Таймауты в миллисекундах
DialTimeout = "10s"
ReadTimeout = "10s"

[JWT]
Token = "test"
ExpiresIn = 3600000000000
SigningMethod = "HS256"